package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import java.util.List;
import java.util.concurrent.TimeUnit;
import me.zhanghai.android.materialprogressbar.BuildConfig;
import org.json.JSONObject;

@qj
/* loaded from: classes.dex */
public final class o {
    private static byte[] ex;
    private static final d<String> cR = d.a(0, "gads:sdk_core_experiment_id");

    /* renamed from: a, reason: collision with root package name */
    public static final d<String> f3306a = d.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static final d<String> cS = d.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final d<Boolean> cT = d.a(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static final d<String> cU = d.a(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final d<String> cV = d.a(0, "gads:request_builder:refresh_if_destroyed:experiment_id");

    /* renamed from: b, reason: collision with root package name */
    public static final d<Boolean> f3307b = d.a(0, "gads:request_builder:refresh_if_destroyed:enable", (Boolean) false);
    private static final d<Boolean> cW = d.a(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static final d<String> cX = d.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final d<Boolean> c = d.a(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final d<Boolean> d = d.a(0, "gads:report_dynamite_crash_in_background_thread", (Boolean) false);
    public static final d<Boolean> e = d.a(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final d<String> f = d.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final d<Float> g = d.a(1, "gads:trapped_exception_sample_rate", 0.01f);
    private static final d<String> cY = d.a(0, "gads:block_autoclicks_experiment_id");
    private static final d<String> cZ = d.a(0, "gads:spam_app_context:experiment_id");
    private static final d<Integer> da = d.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final d<String> h = d.a(1, "gads:video_exo_player:version", "1");
    public static final d<Integer> i = d.a(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final d<Integer> j = d.a(1, "gads:video_exo_player:read_timeout", 8000);
    public static final d<Integer> k = d.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final d<Integer> l = d.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final d<Integer> m = d.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    private static final d<String> db = d.a(0, "gads:video_stream_cache:experiment_id");
    public static final d<Integer> n = d.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final d<Integer> o = d.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final d<Integer> p = d.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final d<Long> q = d.a(1, "gads:video_stream_cache:limit_time_sec", 300L);
    public static final d<Long> r = d.a(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    public static final d<Integer> s = d.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final d<Boolean> t = d.a(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final d<String> u = d.a(1, "gads:video:metric_frame_hash_times", BuildConfig.FLAVOR);
    public static final d<Long> v = d.a(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    public static final d<Boolean> w = d.a(1, "gads:video:force_watermark", (Boolean) false);
    public static final d<Long> x = d.a(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    public static final d<Boolean> y = d.a(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final d<Integer> z = d.a(1, "gads:video:spinner:scale", 4);
    public static final d<Long> A = d.a(1, "gads:video:spinner:jank_threshold_ms", 50L);
    public static final d<Boolean> B = d.a(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final d<Boolean> C = d.a(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final d<String> D = d.a(1, "gads:video:codec_query_mime_types", BuildConfig.FLAVOR);
    public static final d<Integer> E = d.a(1, "gads:video:codec_query_minimum_version", 16);
    private static final d<Float> dc = d.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static final d<String> dd = d.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final d<Boolean> de = d.a(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static final d<Float> df = d.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static final d<Boolean> dg = d.a(0, "gads:ad_id_use_persistent_service:enabled", (Boolean) false);
    private static final d<Boolean> dh = d.a(0, "gads:ad_id:use_ipc:enabled", (Boolean) false);
    public static final d<String> F = d.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final d<String> G = d.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final d<String> H = d.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final d<String> I = d.a(1, "gad:mraid:version", "2.0");
    public static final d<Boolean> J = d.a(1, "gads:mraid:unload", (Boolean) false);
    public static final d<Boolean> K = d.a(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final d<String> L = d.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final d<Boolean> M = d.a(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final d<Boolean> N = d.a(0, "gads:enable_content_fetching", (Boolean) true);
    public static final d<Integer> O = d.a(0, "gads:content_length_weight", 1);
    public static final d<Integer> P = d.a(0, "gads:content_age_weight", 1);
    public static final d<Integer> Q = d.a(0, "gads:min_content_len", 11);
    public static final d<Integer> R = d.a(0, "gads:fingerprint_number", 10);
    public static final d<Integer> S = d.a(0, "gads:sleep_sec", 10);
    public static final d<Integer> T = d.a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final d<Integer> U = d.a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final d<Integer> V = d.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final d<String> W = d.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final d<String> X = d.a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final d<Boolean> Y = d.a(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final d<Boolean> Z = d.a(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final d<Long> aa = d.a(0, "gads:app_index:timeout_ms", 1000L);
    private static final d<String> di = d.a(0, "gads:app_index:experiment_id");
    public static final d<Boolean> ab = d.a(0, "gads:ad_key_enabled", (Boolean) false);
    public static final d<Boolean> ac = d.a(1, "gads:sai:enabled", (Boolean) true);
    public static final d<String> ad = d.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final d<String> ae = d.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final d<Boolean> af = d.a(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final d<String> ag = d.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final d<Long> ah = d.a(1, "gads:sai:timeout_ms", -1L);
    public static final d<Integer> ai = d.a(1, "gads:sai:scion_thread_pool_size", 5);
    private static final d<Boolean> dj = d.a(1, "gads:sai:app_measurement_enabled", (Boolean) false);
    private static final d<Boolean> dk = d.a(1, "gads:sai:force_through_reflection", (Boolean) true);
    public static final d<Boolean> aj = d.a(1, "gads:sai:gmscore_availability_check_disabled", (Boolean) false);
    public static final d<Boolean> ak = d.a(1, "gads:sai:logging_disabled_for_drx", (Boolean) false);
    public static final d<Boolean> al = d.a(1, "gads:interstitial:app_must_be_foreground:enabled", (Boolean) false);
    private static final d<Integer> dl = d.a(0, "gads:webview_cache_version", 0);
    public static final d<Boolean> am = d.a(0, "gads:corewebview:adwebview_factory:enable", (Boolean) false);
    public static final d<Boolean> an = d.a(0, "gads:corewebview:javascript_engine", (Boolean) false);
    public static final d<Boolean> ao = d.a(1, "gad:webview:inject_scripts", (Boolean) false);
    public static final d<Boolean> ap = d.a(0, "gads:webview:permission:disabled", (Boolean) false);
    private static final d<String> dm = d.b(0, "gads:pan:experiment_id");
    private static final d<Boolean> dn = d.a(1, "gads:new_rewarded_ad:enabled", (Boolean) true);
    public static final d<Boolean> aq = d.a(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final d<Long> ar = d.a(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    public static final d<Boolean> as = d.a(1, "gads:rewarded:ad_metadata_enabled", (Boolean) false);
    public static final d<Boolean> at = d.a(1, "gads:rewarded:ssv_custom_data_enabled", (Boolean) true);
    public static final d<Long> au = d.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    public static final d<Long> av = d.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final d<Boolean> aw = d.a(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final d<Long> ax = d.a(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    public static final d<Boolean> ay = d.a(1, "gads:disable_adid_values_in_ms", (Boolean) false);

    /* renamed from: do, reason: not valid java name */
    private static final d<Boolean> f0do = d.a(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final d<Long> az = d.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    public static final d<Boolean> aA = d.a(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final d<Boolean> aB = d.a(1, "gads:disabling_closable_area:enabled", (Boolean) false);
    private static final d<Boolean> dp = d.a(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static final d<String> dq = d.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final d<Integer> dr = d.a(1, "gads:banner_ad_pool:max_queues", 3);
    private static final d<Integer> ds = d.a(1, "gads:banner_ad_pool:max_pools", 3);
    public static final d<Boolean> aC = d.a(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final d<Boolean> aD = d.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final d<String> aE = d.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final d<String> aF = d.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final d<Integer> aG = d.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final d<Integer> aH = d.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final d<Integer> aI = d.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final d<String> aJ = d.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final d<Integer> aK = d.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final d<Integer> aL = d.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final d<Long> aM = d.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    public static final d<Long> aN = d.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    public static final d<Float> aO = d.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final d<Float> aP = d.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final d<Boolean> aQ = d.a(0, "gads:debug_logging_feature:enable", (Boolean) false);
    public static final d<Boolean> aR = d.a(0, "gads:debug_logging_feature:intercept_web_view", (Boolean) false);
    private static final d<Integer> dt = d.a(1, "gads:heap_wastage:bytes", 0);
    public static final d<String> aS = d.a(1, "gads:spherical_video:vertex_shader", BuildConfig.FLAVOR);
    public static final d<String> aT = d.a(1, "gads:spherical_video:fragment_shader", BuildConfig.FLAVOR);
    public static final d<Boolean> aU = d.a(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final d<Boolean> aV = d.a(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final d<Long> aW = d.a(1, "gads:position_watcher:throttle_ms", 200L);
    public static final d<Long> aX = d.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    public static final d<Boolean> aY = d.a(1, "gads:gen204_signals:enabled", (Boolean) false);
    public static final d<Boolean> aZ = d.a(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    private static final d<Boolean> du = d.a(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static final d<Boolean> dv = d.a(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static final d<Boolean> dw = d.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    private static final d<Long> dx = d.a(1, "gads:rtb_signal_timeout_ms", 1000L);
    private static final d<Boolean> dy = d.a(1, "gads:rtb_cld:enabled", (Boolean) false);
    public static final d<Long> ba = d.a(0, "gads:resolve_future:default_timeout_ms", 30000L);
    public static final d<Long> bb = d.a(0, "gads:ad_loader:timeout_ms", 60000L);
    public static final d<Long> bc = d.a(0, "gads:rendering:timeout_ms", 60000L);
    public static final d<Boolean> bd = d.a(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final d<Long> be = d.a(1, "gads:gestures:task_timeout", 2000L);
    public static final d<Boolean> bf = d.a(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final d<Boolean> bg = d.a(1, "gads:gestures:ans:enabled", (Boolean) false);
    public static final d<Boolean> bh = d.a(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final d<Boolean> bi = d.a(1, "gads:gestures:brt:enabled", (Boolean) false);
    public static final d<Boolean> bj = d.a(1, "gads:signal:app_permissions:disabled", (Boolean) false);
    public static final d<Boolean> bk = d.a(1, "gads:gestures:inthex:enabled", (Boolean) false);
    public static final d<Boolean> bl = d.a(1, "gads:gestures:hpk:enabled", (Boolean) true);
    public static final d<String> bm = d.a(1, "gads:gestures:pk", BuildConfig.FLAVOR);
    public static final d<Boolean> bn = d.a(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final d<Boolean> bo = d.a(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final d<Boolean> bp = d.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final d<Boolean> bq = d.a(0, "gass:enabled", (Boolean) true);
    public static final d<Boolean> br = d.a(0, "gass:enable_int_signal", (Boolean) true);
    public static final d<Boolean> bs = d.a(0, "gass:enable_ad_attestation_signal", (Boolean) true);
    private static final d<Boolean> dz = d.a(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static final d<String> dA = d.a(1, "gads:sdk_core_constants:experiment_id");
    public static final d<String> bt = d.a(1, "gads:sdk_core_constants:caps", BuildConfig.FLAVOR);
    public static final d<Long> bu = d.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final d<Boolean> bv = d.a(0, "gads:js_flags:mf", (Boolean) false);
    private static final d<Boolean> dB = d.a(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    public static final d<Boolean> bw = d.a(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final d<String> bx = d.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final d<String> dC = d.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final d<String> dD = d.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final d<String> by = d.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final d<Integer> bz = d.a(1, "gads:native_video_load_timeout", 10);
    public static final d<Integer> bA = d.a(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final d<String> bB = d.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final d<Boolean> bC = d.a(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final d<Boolean> bD = d.a(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final d<Boolean> bE = d.a(1, "gads:native:media_view_match_parent:enabled", (Boolean) false);
    public static final d<Boolean> bF = d.a(1, "gads:native:count_impression_for_assets", (Boolean) false);
    public static final d<Boolean> bG = d.a(1, "gads:native:custom_one_point_five_click:enable", (Boolean) true);
    public static final d<Boolean> bH = d.a(1, "gads:unified_native_ad:enable", (Boolean) true);
    public static final d<Boolean> bI = d.a(1, "gads:instream_ad:enabled", (Boolean) true);
    public static final d<Boolean> bJ = d.a(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    private static final d<Boolean> dE = d.a(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static final d<String> dF = d.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final d<Long> bK = d.a(1, "gads:auto_location_timeout", 2000L);
    private static final d<String> dG = d.b(1, "gads:auto_location_timeout:experiment_id");
    private static final d<Long> dH = d.a(1, "gads:auto_location_interval", -1L);
    private static final d<String> dI = d.b(1, "gads:auto_location_interval:experiment_id");
    private static final d<Boolean> dJ = d.a(0, "gads:auto_location_interval:without_thread", (Boolean) true);
    public static final d<Boolean> bL = d.a(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    private static final d<String> dK = d.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final d<Long> bM = d.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    private static final d<String> dL = d.a(0, "gads:afs:csa:experiment_id");
    public static final d<String> bN = d.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final d<String> bO = d.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final d<String> bP = d.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final d<String> bQ = d.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final d<String> bR = d.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final d<Long> bS = d.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    public static final d<Long> bT = d.a(1, "gads:parental_controls:timeout", 2000L);
    private static final d<String> dM = d.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final d<Long> dN = d.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    public static final d<Boolean> bU = d.a(0, "gads:safe_browsing:debug", (Boolean) false);
    private static final d<Integer> dO = d.a(1, "gads:cache:ad_request_timeout_millis", 250);
    private static final d<Integer> dP = d.a(1, "gads:cache:max_concurrent_downloads", 10);
    private static final d<Long> dQ = d.a(1, "gads:cache:javascript_timeout_millis", 5000L);
    public static final d<Boolean> bV = d.a(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final d<Boolean> bW = d.a(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final d<Boolean> bX = d.a(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final d<Long> bY = d.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final d<Boolean> bZ = d.a(1, "gads:cache:use_cache_data_source", (Boolean) false);
    public static final d<Boolean> ca = d.a(1, "gads:cache:connection_per_read", (Boolean) false);
    public static final d<Long> cb = d.a(1, "gads:cache:connection_timeout", 5000L);
    public static final d<Long> cc = d.a(1, "gads:cache:read_only_connection_timeout", 5000L);
    public static final d<Boolean> cd = d.a(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final d<String> ce = d.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final d<Integer> cf = d.a(1, "gads:http_assets_cache:time_out", 100);
    public static final d<Boolean> cg = d.a(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final d<Boolean> ch = d.a(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final d<Boolean> ci = d.a(1, "gads:debug_hold_gesture:enabled", (Boolean) false);
    public static final d<Long> cj = d.a(1, "gads:debug_hold_gesture:time_millis", 2000L);
    public static final d<String> ck = d.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final d<String> cl = d.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final d<String> cm = d.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final d<String> cn = d.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final d<Integer> co = d.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final d<Integer> cp = d.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final d<Boolean> cq = d.a(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final d<Boolean> cr = d.a(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final d<Boolean> cs = d.a(1, "gad:interstitial_multi_window_method", (Boolean) false);
    public static final d<Integer> ct = d.a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final d<Boolean> cu = d.a(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final d<Boolean> cv = d.a(1, "gads:clearcut_logging:write_to_file", (Boolean) false);
    public static final d<Boolean> cw = d.a(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);
    public static final d<Boolean> cx = d.a(1, "gad:publisher_testing:force_local_request:enabled", (Boolean) false);
    public static final d<String> cy = d.a(1, "gad:publisher_testing:force_local_request:enabled_list", BuildConfig.FLAVOR);
    public static final d<String> cz = d.a(1, "gad:publisher_testing:force_local_request:disabled_list", BuildConfig.FLAVOR);
    public static final d<Boolean> cA = d.a(0, "gad:force_dynamite_loading_enabled", (Boolean) false);
    private static final d<String> dR = d.a(0, "gad:dynamite_module:experiment_id");
    public static final d<Integer> cB = d.a(1, "gad:http_redirect_max_count:times", 8);
    public static final d<Boolean> cC = d.a(1, "gads:omid:enabled", (Boolean) false);
    public static final d<Integer> cD = d.a(1, "gads:omid:destroy_webview_delay", 1000);
    private static final d<Boolean> dS = d.a(0, "gads:nonagon:red_button", (Boolean) false);
    private static final d<Boolean> dT = d.a(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static final d<String> dU = d.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final d<Boolean> dV = d.a(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static final d<String> dW = d.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final d<Boolean> dX = d.a(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    private static final d<Boolean> dY = d.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    private static final d<String> dZ = d.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final d<Boolean> ea = d.a(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static final d<String> eb = d.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final d<Boolean> cE = d.a(1, "gads:nonagon:banner:check_dp_size", (Boolean) false);
    private static final d<Boolean> ec = d.a(1, "gads:nonagon:rewarded:load_multiple_ads", (Boolean) true);
    public static final d<Boolean> cF = d.a(1, "gads:nonagon:return_last_error_code", (Boolean) false);
    private static final d<Boolean> ed = d.a(1, "gads:nonagon:return_no_fill_error_code", (Boolean) false);
    private static final d<Boolean> ee = d.a(1, "gads:nonagon:continue_on_no_fill", (Boolean) false);
    public static final d<Boolean> cG = d.a(1, "gads:nonagon:open_not_loaded_interstitial", (Boolean) true);
    private static final d<Boolean> ef = d.a(1, "gads:nonagon:separate_timeout:enabled", (Boolean) false);
    private static final d<Integer> eg = d.a(1, "gads:nonagon:request_timeout:seconds", 60);
    private static final d<Boolean> eh = d.a(0, "gads:nonagon:limit_ad_request_connection", (Boolean) true);
    private static final d<Boolean> ei = d.a(1, "gads:nonagon:javascript_ad_request:enabled", (Boolean) false);
    private static final d<Boolean> ej = d.a(1, "gads:nonagon:service:enabled", (Boolean) false);
    private static final d<Boolean> ek = d.a(1, "gads:signals:ad_id_info:enabled", (Boolean) false);
    private static final d<Boolean> el = d.a(1, "gads:signals:app_index:enabled", (Boolean) false);
    private static final d<Boolean> em = d.a(1, "gads:signals:cache:enabled", (Boolean) false);
    private static final d<Boolean> en = d.a(1, "gads:signals:doritos:enabled", (Boolean) false);
    public static final d<Boolean> cH = d.a(1, "gads:signals:doritos:v1:enabled", (Boolean) false);
    private static final d<Boolean> eo = d.a(1, "gads:signals:location:enabled", (Boolean) false);
    private static final d<Boolean> ep = d.a(1, "gads:signals:network_prediction:enabled", (Boolean) false);
    private static final d<Boolean> eq = d.a(1, "gads:signals:parental_control:enabled", (Boolean) false);
    private static final d<Boolean> er = d.a(1, "gads:signals:video_decoder:enabled", (Boolean) false);
    public static final d<Long> cI = d.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
    public static final d<String> cJ = d.a(0, "gads:public_beta:traffic_multiplier", "1.0");
    public static final d<Integer> cK = d.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final d<Integer> cL = d.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final d<Integer> cM = d.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final d<Integer> cN = d.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static final d<Boolean> es = d.a(0, "gads:rewarded_sku:enabled", (Boolean) true);
    private static final d<Boolean> et = d.a(0, "gads:rewarded_sku:override_test:enabled", (Boolean) false);
    public static final d<Boolean> cO = d.a(1, "gads:consent:shared_preference_reading:enabled", (Boolean) true);
    public static final d<Boolean> cP = d.a(1, "gads:consent:iab_consent_info:enabled", (Boolean) true);
    private static final d<Boolean> eu = d.a(1, "gads:nativeads:image:sample:enabled", (Boolean) true);
    private static final d<Integer> ev = d.a(1, "gads:nativeads:image:sample:pixels", 1048576);
    public static final d<Integer> cQ = d.a(0, "gads:dynamite_load:fail:sample_rate", 10000);
    private static final d<Boolean> ew = d.a(0, "gads:service:webview:enable_directory_suffix", (Boolean) true);

    public static void a(Context context) {
        zt.a(context, new p(context));
        int iIntValue = ((Integer) bra.e().a(dt)).intValue();
        if (iIntValue <= 0 || ex != null) {
            return;
        }
        ex = new byte[iIntValue];
    }

    public static void a(Context context, int i2, JSONObject jSONObject) {
        bra.c();
        SharedPreferences.Editor editorEdit = context.getSharedPreferences("google_ads_flags", 0).edit();
        bra.d().a(editorEdit, 1, jSONObject);
        bra.c();
        editorEdit.commit();
    }

    public static List<String> a() {
        return bra.d().a();
    }

    public static List<String> b() {
        return bra.d().b();
    }
}
